# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: anemona.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'anemona.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ranemona.proto\x12\x07\x61nemona\"\"\n\rSignalRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"\xd3\x01\n\x10MultiplierUpdate\x12\x1a\n\x12\x65xact_timestamp_ms\x18\x01 \x01(\x03\x12 \n\x18raw_current_alpha_factor\x18\x02 \x01(\x01\x12$\n\x1cterminal_position_multiplier\x18\x04 \x01(\x01\x12&\n\x1esevere_macro_rebalance_warning\x18\x05 \x01(\x08\x12\x1a\n\x12\x65vent_impact_level\x18\x06 \x01(\x05\x12\x17\n\x0f\x65vent_sentiment\x18\x07 \x01(\x01\x32h\n\x11\x41lphaSignalEngine\x12S\n\x1cSubscribePositionMultipliers\x12\x16.anemona.SignalRequest\x1a\x19.anemona.MultiplierUpdate0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'anemona_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SIGNALREQUEST']._serialized_start=26
  _globals['_SIGNALREQUEST']._serialized_end=60
  _globals['_MULTIPLIERUPDATE']._serialized_start=63
  _globals['_MULTIPLIERUPDATE']._serialized_end=274
  _globals['_ALPHASIGNALENGINE']._serialized_start=276
  _globals['_ALPHASIGNALENGINE']._serialized_end=380
# @@protoc_insertion_point(module_scope)
